//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using NHibernate.Linq;
using NHibernate.Util;
using Remotion.Linq.Parsing.ExpressionVisitors;

namespace NHibernate
{
	using System.Threading.Tasks;
	using System.Threading;
	public partial class MultiAnyLinqQuery<T> : MultiAnyQuery<T>
	{

		protected override async Task<IList<T>> ExecuteQueryNowAsync(CancellationToken cancellationToken = default(CancellationToken))
		{
			cancellationToken.ThrowIfCancellationRequested();
			if (_postExecuteTransformer == null)
			{
				return await (base.ExecuteQueryNowAsync(cancellationToken)).ConfigureAwait(false);
			}

			return GetTransformedResults(await (Query.ListAsync(cancellationToken)).ConfigureAwait(false));
		}
	}
}
